from __future__ import annotations

from pathlib import Path

from codas.app.render_util import guard_table_cell
from codas.config.loader import load_policies
from codas.structure.loader import load_structure_map
from codas.structure.models import StructureMap

# The Codas-managed region of AGENTS.md. Everything OUTSIDE these markers (the Trellis
# block, hand-authored sections) is preserved verbatim on every write; only the bytes
# BETWEEN them are a deterministic projection of `.codas/policies.yml` + `.codas/structure.yml`.
# Mirrors the Trellis block convention already in AGENTS.md so the two managed regions coexist.
BLOCK_START = "<!-- CODAS:START -->"
BLOCK_END = "<!-- CODAS:END -->"

_GENERATED_NOTE = (
    "<!-- GENERATED by `codas agents --write` from .codas/policies.yml + "
    ".codas/structure.yml. Do not hand-edit; regenerate to refresh. -->"
)

# A curated one-line "what it catches" per policy id. STATIC (not the policies.yml prose):
# the prose carries slash+extension path spans (e.g. .codas/claims.yml) that, rendered into
# the scanned AGENTS.md, would become `doc_claim`s and churn the inventory hash (must-hold #4).
# These blurbs are plain prose — no backticked/linked extension-bearing paths — so the block
# adds ZERO new doc_claims. A policy declared in policies.yml without a blurb is a hard error
# (forces curation; keeps the catalog honest, like `policy_registry` keeps code↔config honest).
_POLICY_BLURB = {
    "policy_registry": "Declared policies and implemented checks must stay in 1:1 agreement.",
    "duplicate_concept": "A second implementation of an existing concept needs a waiver.",
    "duplicate_symbol": "A public top-level name repeated across modules (detection signal; "
    "enforcement is duplicate_implementation).",
    "duplicate_implementation": "A top-level symbol defined in two or more modules must "
    "declare a canonical, variant or migration relationship in the claim set.",
    "orphan_artifact": "A new file must have an owner, a purpose and a place in the architecture.",
    "stale_claim": "A Markdown link or code-span path reference must point to an existing path.",
    "stale_html_claim": "A path reference in a governed HTML doc must point to an existing path.",
    "stale_wiki_claim": "An Atlas Wiki claim must resolve against repo facts (canonical-source "
    "and evidence paths must exist).",
    "fact_coupling": "When a watched symbol, import or call changes, its required companion "
    "path must co-change in the same diff.",
    "code_anchor": "A defines/calls/contains claim in a hand-authored code-wiki page must "
    "resolve against current facts (open-world warning).",
    "generated_wiki_drift": "A committed generated Atlas page must match the Structure Map and "
    "Program Plan facts and carry a fresh source hash.",
    "missing_canonical_owner": "A new concept must declare its owner before implementation.",
    "missing_structure_owner": "A changed file in a governed path must map to a Structure-Map "
    "unit with an owner.",
    "structure_drift": "Repository changes must stay aligned with the Structure Map or update "
    "it explicitly.",
    "deprecated_path_used": "A new artifact must not be added under a deprecated or removed path.",
    "dependency_direction": "A module must not import a unit its owner declares must-not-"
    "depend-on.",
    "constraint_conflict": "Conflicting authoritative claims must be resolved or waived.",
    "stale_preflight": "An agent must state the affected concept and read canonical sources "
    "before editing.",
    "config_sources": "Declared authoritative and supporting constraint sources must exist on disk.",
    "structure_map": "The Structure Map must load as a valid schema.",
    "program_plan": "The Program Plan must load as a valid schema.",
    "document_set": "The Document Role Manifest required roles must be present, exist and not "
    "out-rank config authority.",
    "trellis_context": "The configured Trellis workflow context must be present and well-formed.",
    "dogfooding_protocol": "The repository must satisfy its own declared dogfooding protocol.",
    "waivers": "Each waiver must declare a reason, owner, scope and expiry.",
}

# The design-quality failures NO active policy catches today — the gate is SILENT, so the
# injected map is the only defense (the two-tier framing: GATE guarantees hard invariants;
# INJECTION is load-bearing for these). Static prose; matches the policies.yml R7 commentary.
_UNGATEABLE_CLASSES = (
    "Wrong unit but still owned — code placed in an owned path that is the wrong subsystem "
    "(missing_structure_owner only checks that SOME unit owns it, not that it is the RIGHT one).",
    "Semantic reuse miss — re-implementing a concept that already exists "
    "(duplicate_concept is planned; duplicate_symbol only flags exact top-level name clashes).",
    "Wrong abstraction or hook point — a change that type-checks and is owned but sits at the "
    "wrong layer or seam.",
)


def _enforcement(severity: str | None, status: str | None) -> str:
    """Derive how the gate treats a policy, from its declared (severity, status):

      - ``planned``  — declared on the roadmap, NOT yet implemented (the gate never runs it).
      - ``gated``    — an error the gate blocks on (via ``check``, ``wiki --verify`` or the
                       byte-identical inventory).
      - ``advisory`` — a warning the gate SURFACES but does not block on.

    Purely a projection of the two declared fields, so the agent learns exactly which failure
    classes the gate is silent on without a second hand-maintained classification.
    """
    if status == "planned":
        return "planned"
    if severity == "error":
        return "gated"
    return "advisory"


def _blurb(policy_id: str) -> str:
    try:
        return _POLICY_BLURB[policy_id]
    except KeyError as error:  # pragma: no cover - exercised via render on a new policy
        raise ValueError(
            f"policy {policy_id!r} is declared in policies.yml but has no AGENTS blurb in "
            "agents_block._POLICY_BLURB; add a one-line 'what it catches' (no slash+extension "
            "path spans) so the governance block stays in sync with the policy registry"
        ) from error


def render_codas_block(policies_raw: dict, structure_map: StructureMap) -> str:
    """Render the Codas governance block (between the markers) as a PURE, deterministic
    projection of the policy registry + Structure Map. Sorted, no timestamp, byte-identical
    for identical inputs.

    must-hold #4: extension-bearing paths (unit paths like ``.codas/structure.yml``) are
    rendered as PLAIN table cells — never inside backticks or markdown links — so the scanned
    AGENTS.md gains no new ``doc_claim`` and the block is inventory-hash-neutral. Backticks are
    used only on claim-safe tokens (policy ids, unit ids, extension-less command names).
    """
    declared = policies_raw.get("policies", {}) or {}
    policy_rows = sorted(
        (
            (
                pid,
                (body or {}).get("severity"),
                _enforcement((body or {}).get("severity"), (body or {}).get("status")),
                _blurb(pid),
            )
            for pid, body in declared.items()
        ),
        key=lambda row: row[0],
    )

    lines = [
        BLOCK_START,
        _GENERATED_NOTE,
        "",
        "# Codas governance",
        "",
        "This repository is governed by Codas (Code Atlas System). Before changing code, read",
        "this map and query the live atlas — do NOT trust your inferred structure over the",
        "verified facts. This block is regenerated from the policy registry and Structure Map;",
        "edits inside the markers are overwritten.",
        "",
        "## Policy catalog",
        "",
        "How the gate treats each policy: **gated** = an error it blocks on; **advisory** = a",
        "warning it surfaces; **planned** = declared but not yet enforced.",
        "",
        "| policy | severity | enforcement | what it catches |",
        "| --- | --- | --- | --- |",
    ]
    for pid, severity, enforcement, blurb in policy_rows:
        lines.append(
            "| `{}` | {} | {} | {} |".format(
                guard_table_cell(pid),
                guard_table_cell(severity or "—"),
                enforcement,
                guard_table_cell(blurb),
            )
        )

    lines += [
        "",
        "## Ungateable failure classes (the gate is SILENT here)",
        "",
        "The gate formalizes only a subset of correctness. These design-quality failures are",
        "caught by NO active policy today — the ownership map below and a reuse query are your",
        "only defense, so verify them yourself before writing:",
        "",
    ]
    lines += [f"- {_ungateable}" for _ungateable in _UNGATEABLE_CLASSES]

    lines += [
        "",
        "## Ownership & placement map",
        "",
        "Every governed path maps to a Structure-Map unit and owner. A changed file must map to",
        "a unit (missing_structure_owner); WHERE within an owned area a change belongs is the",
        "canonical-placement rule the gate cannot enforce — read it before adding files.",
        "",
        "| unit | path | owner | canonical placement |",
        "| --- | --- | --- | --- |",
    ]
    for unit in sorted(structure_map.units, key=lambda u: u.id):
        lines.append(
            "| `{}` | {} | {} | {} |".format(
                guard_table_cell(unit.id),
                guard_table_cell(unit.path),  # PLAIN — extension-bearing paths must not be claims
                guard_table_cell(unit.owner),
                guard_table_cell(unit.canonical_placement),
            )
        )

    lines += [
        "",
        "## Lookup protocol",
        "",
        "The live atlas is fresh and deterministic. Query it (the rendered `wiki/` book is for",
        "humans; these commands are the agent's table):",
        "",
        "- `codas preflight --task <id>` — read-first context, reuse candidates and affected units.",
        "- `codas query <kind>` — one fact block (symbols, imports, calls, units, …); add",
        "  `--select FIELD=VALUE` to filter.",
        "- `codas impact <symbol-or-path>` — what transitively calls a symbol or file.",
        "- `codas schema` — the queryable fact and field shape.",
        "- `codas check .` — the gate; run it before you commit.",
        "",
        BLOCK_END,
    ]
    return "\n".join(lines)


def splice_managed_block(existing: str, block: str) -> str:
    """Splice ``block`` (which itself includes the START/END markers) into ``existing``,
    preserving every byte OUTSIDE the markers. If the markers are present the region between
    them (inclusive) is replaced; otherwise the block is appended after the existing content.
    Deterministic and idempotent: re-splicing identical inputs reproduces identical bytes."""
    if BLOCK_START in existing and BLOCK_END in existing:
        pre, _, rest = existing.partition(BLOCK_START)
        _, _, post = rest.partition(BLOCK_END)
        return pre + block + post
    base = existing.rstrip("\n")
    if base:
        return f"{base}\n\n{block}\n"
    return f"{block}\n"


def agents_pages(repo: Path) -> dict[Path, str]:
    """The deterministic ``{AGENTS.md path: full spliced content}`` shared by write/verify.

    Reads the live policy registry + Structure Map, renders the Codas block, and splices it
    into the EXISTING AGENTS.md (preserving the Trellis block + hand content). A missing
    AGENTS.md yields a new file holding only the Codas block.
    """
    policies_raw = load_policies(repo / ".codas" / "policies.yml")
    structure_map = load_structure_map(repo / ".codas" / "structure.yml")
    block = render_codas_block(policies_raw, structure_map)
    agents_path = repo / "AGENTS.md"
    existing = (
        agents_path.read_text(encoding="utf-8") if agents_path.is_file() else ""
    )
    return {agents_path: splice_managed_block(existing, block)}


def write_agents_block(repo: Path) -> list[Path]:
    """Render and write the AGENTS.md Codas block; return the written paths (sorted).
    write_bytes pins UTF-8 + LF (text mode would translate LF to os.linesep on Windows,
    breaking byte-identical)."""
    written: list[Path] = []
    for path, content in agents_pages(repo).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
        written.append(path)
    return sorted(written)


def verify_agents_block(repo: Path) -> list[Path]:
    """AGENTS.md whose on-disk bytes differ from a fresh splice (the Codas block is stale,
    hand-edited, or missing); empty == up to date. Byte-compare IS the verifier — the block
    carries no machine-checked claims, freshness rides in the rendered bytes. Edits OUTSIDE the
    markers never flag (the expected content is the fresh block spliced over the current file)."""
    stale: list[Path] = []
    for path, content in agents_pages(repo).items():
        if not path.is_file() or path.read_bytes() != content.encode("utf-8"):
            stale.append(path)
    return sorted(stale)
