from __future__ import annotations

from pathlib import Path
from typing import Any

from codas.app.inventory import run_inventory
from codas.app.render_util import mermaid_label
from codas.app.wiki import _PRODUCT_ROOTS_DEFAULT, project_atlas_tree
from codas.app.wiki import product_roots as _resolve_product_roots
from codas.config.loader import load_codas_config
from codas.facts.openworld import open_world_gaps

# W4a — the HUMAN BOOK renderer. Renders the root `wiki/` chapter-book: a deterministic,
# GitHub-browsable knowledge base for PEOPLE (agents read the FEED + .codas/wiki/ claims;
# `wiki/` is for the reader). A PURE projection of the inventory dict — like
# `project_atlas_pack`/`project_atlas_tree`: no LLM (§17), no ScanContext, no adapter import
# (§11). The book is hash-EXCLUDED at the scanner (structure/index._DERIVED_OUTPUT_PREFIXES),
# so it never enters the byte-identical inventory; its freshness is `codas wiki --verify`
# byte-compare. Renders ONLY stable source facts (unit id/path/owner, the knowledge-tree
# slice, import edges) — NEVER volatile observations (e.g. artifact_count) — so a chapter
# restales EXACTLY when its source facts move, with no embedded freshness hash needed (the
# byte-compare IS the verifier). W4a renders the index + ONE chapter; W4b loops all units.

BOOK_ROOT = "wiki"  # the reserved derived-output prefix (see structure/index.py)

# W6: per-unit "why" prose is hand-authored under here as `<unit-id>.md`. The renderer weaves
# its prose (claims fence stripped) into the chapter as `## Overview`. OUT of the inventory
# hash (the code-wiki subtree is excluded), so the book stays a deterministic render of
# (facts + committed prose). Hardcoded like BOOK_ROOT; W7 config-drives it.
_CODE_WIKI_ROOT = ".codas/wiki/code"

_GENERATED_NOTE = (
    "<!-- GENERATED by `codas wiki --write`. Do not edit by hand; regenerate to refresh. -->"
)


def _strip_claims_block(text: str) -> str:
    """Return the page PROSE with every fenced ```` ```atlas:claims ```` block removed (the
    claims are machine data verified by ``code_anchor``, not human book text). Fence-aware,
    deterministic; the surrounding prose is kept verbatim and stripped of trailing blank lines."""
    out: list[str] = []
    in_block = False
    for raw in text.splitlines():
        stripped = raw.strip()
        if not in_block:
            if stripped.startswith("```") and stripped[3:].strip() == "atlas:claims":
                in_block = True
                continue
            out.append(raw)
        elif stripped.startswith("```") and not stripped.strip("`"):
            # close ONLY on a BARE fence (``` with no trailing tag) — a ```python/```nested
            # line inside the block must NOT terminate the strip early (codex; aligned with
            # the semantic claim parser's close rule).
            in_block = False
    return "\n".join(out).strip()


def _read_chapter_prose(repo: Path, unit_id: str) -> str:
    """The authored "why" prose for ``unit_id``'s chapter, or ``""`` if none is committed.
    Reads ``.codas/wiki/code/<unit-id>.md`` (out-of-hash advisory source) and strips its
    claims fence. UTF-8 pinned; a missing page is simply no prose (skeleton-only chapter)."""
    page = repo / _CODE_WIKI_ROOT / f"{unit_id}.md"
    if not page.is_file():
        return ""
    return _strip_claims_block(page.read_text(encoding="utf-8"))


def _open_world_banner(family: str) -> str:
    """The visible open-world lower-bound caveat for a tree-derived section. A rendered
    symbol/edge list must never read as complete (mirrors `codas impact`/views)."""
    misses = "; ".join(open_world_gaps(family))
    return (
        f"> **Open-world.** The structure below is a sound LOWER BOUND — an absent "
        f"function, method, or edge is not proof of absence (static facts under-approximate; "
        f"see `codas impact`). Misses: {misses}"
    )


def _chapter_filename(unit_id: str) -> str:
    """The repo-relative book path for a unit's chapter. Unit ids are kebab tokens (no
    slash), so this is a flat, filesystem-safe name under the book root."""
    return f"{BOOK_ROOT}/{unit_id}.md"


def _unit_by_id(units: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {unit["id"]: unit for unit in units}


def _under_path(path: str, prefix: str) -> bool:
    return path == prefix or path.startswith(prefix + "/")


def _render_symbol_tree(tree: dict[str, dict[str, Any]], node_id: str, depth: int) -> list[str]:
    """Render a knowledge-tree node and its children as a nested markdown bullet list,
    deterministic (children are pre-sorted in the tree). Shows the symbol name + kind, not
    the full node-id, for readability; module/package nodes are handled by the caller."""
    node = tree.get(node_id)
    if node is None:
        return []
    label = node.get("symbol") or node_id
    indent = "  " * depth
    line = f"{indent}- `{label}` *({node['kind']})*"
    out = [line]
    for child in node.get("children") or ():  # pre-sorted
        child_node = tree.get(child)
        # Only descend into symbol-bearing children (class -> method, etc.); module/package
        # nesting is rendered by the chapter's module loop, not here.
        if child_node is not None and child_node["kind"] not in ("module", "package"):
            out += _render_symbol_tree(tree, child, depth + 1)
    return out


def _render_chapter(
    unit: dict[str, Any],
    tree: dict[str, dict[str, Any]],
    imports: list[dict[str, Any]],
    prose: str = "",
) -> str:
    """Render one subsystem chapter: heading + owner + the authored ``## Overview`` prose (if
    any) + the module->symbol tree-slice + a dependency mermaid + the open-world banner. Pure
    and deterministic — ``prose`` is the committed, out-of-hash source text (W6)."""
    unit_id = unit["id"]
    unit_path = unit["path"]
    lines = [
        _GENERATED_NOTE,
        "",
        f"# {unit_id}",
        "",
        f"- **Path:** `{unit_path}`",
        f"- **Owner:** {unit['owner']}",
        f"- **Kind:** {unit['kind']}",
        "",
    ]
    # W6: weave the authored "why" prose (skeleton-first — only when a source page exists).
    if prose:
        lines += ["## Overview", "", prose, ""]
    lines += [
        _open_world_banner("calls"),
        "",
        "## Modules & symbols",
        "",
    ]

    # Modules owned by this unit (longest-prefix ownership already baked into the tree's
    # unit_id), sorted by path. Under each, its top-level symbols (the module node's
    # children), recursively expanding classes into methods.
    module_nodes = sorted(
        nid
        for nid, node in tree.items()
        if node["kind"] == "module" and node.get("unit_id") == unit_id
    )
    if not module_nodes:
        lines.append("_No module-level symbols in this unit._")
    for module_id in module_nodes:
        lines.append(f"### `{module_id}`")
        lines.append("")
        module = tree[module_id]
        children = [
            child
            for child in (module.get("children") or ())
            if tree.get(child) and tree[child]["kind"] not in ("module", "package")
        ]
        if not children:
            lines.append("_(no top-level symbols)_")
        for child in children:  # pre-sorted
            lines += _render_symbol_tree(tree, child, 0)
        lines.append("")

    # Dependency graph: first-party import edges originating in this unit's path.
    edges = sorted(
        (
            edge
            for edge in imports
            if edge.get("target_path") and _under_path(edge["module"], unit_path)
        ),
        key=lambda e: (e["module"], e["target_path"], e["target"]),
    )
    lines += ["## Dependencies", ""]
    if not edges:
        lines += ["_No first-party import edges originate in this unit._", ""]
    else:
        nodes = sorted({e["module"] for e in edges} | {e["target_path"] for e in edges})
        node_id = {path: f"n{i}" for i, path in enumerate(nodes)}
        lines.append("```mermaid")
        lines.append("graph LR")
        for path in nodes:
            lines.append(f'  {node_id[path]}["{mermaid_label(path)}"]')
        for edge in edges:
            lines.append(f"  {node_id[edge['module']]} --> {node_id[edge['target_path']]}")
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def _render_index(units: list[dict[str, Any]], rendered_ids: tuple[str, ...]) -> str:
    """Render the book index: overview + a nav table of every unit (id/path/owner), linking
    the units that have a rendered chapter and listing the rest plain (no dead links)."""
    lines = [
        _GENERATED_NOTE,
        "",
        "# Codas Atlas Book",
        "",
        "A deterministic, GitHub-browsable knowledge base rendered from verified repository",
        "facts by `codas wiki --write`. This book is for human readers; agents consume the",
        "structured FEED (`codas wiki --emit-feed`) and the `.codas/wiki/` claim surface.",
        "",
        _open_world_banner("calls"),
        "",
        "## Subsystems",
        "",
        "| subsystem | path | owner |",
        "| --- | --- | --- |",
    ]
    for unit in sorted(units, key=lambda u: u["id"]):
        unit_id = unit["id"]
        if unit_id in rendered_ids:
            name = f"[{unit_id}]({unit_id}.md)"
        else:
            name = unit_id
        lines.append(f"| {name} | `{unit['path']}` | {unit['owner']} |")
    lines.append("")
    return "\n".join(lines)


def _chapter_unit_ids(
    tree: dict[str, dict[str, Any]], by_id: dict[str, dict[str, Any]]
) -> tuple[str, ...]:
    """The code units to render as chapters: every Structure-Map unit that OWNS ≥1
    knowledge-tree node (product symbols/calls), sorted, deterministic. Derived — not a
    hardcoded list — so the set tracks the repo: it auto-includes every code subsystem and
    auto-excludes non-code / empty / not-on-disk units (they own no nodes), which stay index
    entries rather than tree-less chapters. Runs on ANY repo without configuration."""
    owning = {node.get("unit_id") for node in tree.values() if node.get("unit_id")}
    return tuple(sorted(uid for uid in owning if uid in by_id))


def project_book(
    inventory: dict[str, Any],
    prose_by_unit: dict[str, str] | None = None,
    product_roots: tuple[str, ...] = _PRODUCT_ROOTS_DEFAULT,
) -> dict[str, str]:
    """Project an inventory dict (+ optional per-unit authored prose) into the book pages
    ``{repo-relative path: content}`` (pure, no I/O). The index + one chapter per code unit
    (see :func:`_chapter_unit_ids`). Deterministic by construction — ``prose_by_unit`` maps a
    unit id to its committed ``## Overview`` text (empty/absent → skeleton-only chapter);
    ``product_roots`` scopes the knowledge tree (config-driven via :func:`book_pages`)."""
    units = inventory.get("units") or []
    tree = project_atlas_tree(inventory, product_roots)["tree"]
    imports = (inventory.get("imports") or {}).get("edges") or []
    by_id = _unit_by_id(units)
    prose_by_unit = prose_by_unit or {}

    chapter_ids = _chapter_unit_ids(tree, by_id)
    chapters = {
        _chapter_filename(uid): _render_chapter(
            by_id[uid], tree, imports, prose_by_unit.get(uid, "")
        )
        for uid in chapter_ids
    }

    pages: dict[str, str] = {f"{BOOK_ROOT}/index.md": _render_index(units, chapter_ids)}
    pages.update(chapters)
    return pages


def book_pages(repo: Path) -> dict[Path, str]:
    """The deterministic ``{absolute path: content}`` for every book page — the single render
    source shared by ``--write`` and ``--verify``. The inventory already excludes the book
    (scanner-level ``_DERIVED_OUTPUT_PREFIXES``), so the book never feeds its own render. Reads
    the authored ``.codas/wiki/code/<unit>.md`` prose (out-of-hash) to weave each chapter."""
    inventory = run_inventory(repo)
    by_id = _unit_by_id(inventory.get("units") or [])
    prose_by_unit = {uid: _read_chapter_prose(repo, uid) for uid in by_id}
    roots = _resolve_product_roots(load_codas_config(repo / ".codas" / "config.yml").raw)
    return {
        repo / rel: content
        for rel, content in project_book(inventory, prose_by_unit, roots).items()
    }


def write_book(repo: Path) -> list[Path]:
    """Render and write the book pages; return the written paths (sorted). Idempotent:
    identical bytes on a re-run when the source facts are unchanged. write_bytes pins UTF-8 +
    LF so the bytes are platform-independent (text mode would translate ``\\n`` to os.linesep
    on write, breaking byte-identical on Windows)."""
    written: list[Path] = []
    for page, content in book_pages(repo).items():
        page.parent.mkdir(parents=True, exist_ok=True)
        page.write_bytes(content.encode("utf-8"))
        written.append(page)
    return sorted(written)


def verify_book(repo: Path) -> list[Path]:
    """Book pages whose on-disk bytes differ from a fresh render (stale, hand-edited, OR an
    orphan no longer rendered); empty == all up to date. Byte-compare IS the book's verifier
    (the pages carry no machine-checked claim block; freshness rides in the rendered bytes)."""
    expected = book_pages(repo)
    stale: list[Path] = []
    for page, content in expected.items():
        if not page.exists() or page.read_bytes() != content.encode("utf-8"):
            stale.append(page)
    # Orphans: a committed wiki/*.md no longer in the expected set (e.g. a chapter dropped
    # from _CHAPTER_UNITS) lingers on disk; regenerating never removes it, so --verify must
    # flag it or the book silently drifts from the live unit set (codex).
    book_dir = repo / BOOK_ROOT
    if book_dir.is_dir():
        for found in book_dir.glob("*.md"):
            if found not in expected:
                stale.append(found)
    return sorted(stale)
